### ISSUE TITLE
Specific Blogpost Missing

### ISSUE THREAD

**Issue by the-real-kenna** [balena-io/balena-blog#289]
I have a bookmark for a blogpost I used to reference quite a lot and it appears to be missing now.

The link to the post was: https://www.balena.io/blog/support-driven-development/

When the page loads, the message says: 
> NOT FOUND
> You just hit a route that doesn't exist... the sadness.

**Comment by Lizzieepton** [comment]
Hi @the-real-kenna - I think when i asked you to create the issue I might have asked you to see if you could find the blog in the list here: https://github.com/balena-io/balena-blog/tree/master/src/pages/blog I've just tried to find it and can't just wondering if you can? Otherwise we don't have the original post copy anywhere so I don't think we will be able to get it back up and running...

**Comment by Lizzieepton** [comment]
Archive of the blog post provided by Kenna here: http://web.archive.org/web/20210710151140/https://www.balena.io/blog/support-driven-development/ - Need to repost and backdate this article for it to appear on the blog

**Comment by Lizzieepton** [comment]
Closed with the attached PR
